### ISSUE TITLE
Import transactions : handle various banks csv/xlsx files

### ISSUE THREAD

**Issue by mtb0x1** [Bone008/finance-tracker#126]
Hi,

Is it possible to add support to import transaction functionality to other banks ? (currently only Kreissparkasse CAMT and MPL are supported)

The idea would be to either implement the mapping for the most known banks out there (Deutch Bank, HSBC ... etc) or when the format is not recognized when importing, the system request to map manually columns : a pop-up with all mandatory fields to populate when importing + list of available fields of the file to import. (something like [this](https://i.stack.imgur.com/jHYJv.png))

Regards

**Comment by Bone008** [comment]
Yes, a UI allowing a custom mapping between CSV columns and the internal data model would be ideal and is planned eventually. For now, since the current users of the tool are very limited, the supported formats are hardcoded [in this file](https://github.com/Bone008/finance-tracker/blob/master/src/app/money/transactions/form-import/mappings.ts) and new ones can be manually added, either by creating a pull request or sending me an example CSV file for the bank you need.
