### ISSUE TITLE
Bug: auto completion doesn't work with mouse click.

### ISSUE THREAD

**Issue by Taimonania** [Bone008/finance-tracker#127]
Behavior: 
I want to add a new label "leben/essen/supermarkt" to a transaction without any labels. I type "super" and the auto completion suggests "leben/essen/supermarkt", but when I click on the suggestion only the label "super" is added to the transaction. It works when using ENTER on the keyboard.

How to recreate: 
Take a transaction and delete all labels (or create a new transaction), type something that triggers auto completion, then click with the mouse on the suggestion. It will not add the clicked label, but only a label with the string that was typed before.

**Comment by Bone008** [comment]
Can reproduce. Looks like I never select suggestions with the mouse, so I never noticed ... If you click "fast enough" 

Caused by automatically adding the entered label when the text field loses focus, introduced by 6cb210073172e65bfd060c324b3900ca42e41561. The change was supposed to make adding labels in the "add transaction" dialog on mobile less annoying.
