### ISSUE TITLE
Bug: filtering for "-amount:0" results in a grouped transaction with amount of 0 still showing

### ISSUE THREAD

**Issue by Taimonania** [Bone008/finance-tracker#181]
When I am in the "Transaction"-view and filter for "label:leihe -amount:0" to show all transactions that have an amount unequal to 0, I still see a grouped transaction which amount is 0. See the attached screenshot for how the transaction looks like.
At the same time there are other grouped transactions with an amount of 0 that aren't shown. So it seems like this specific transaction is the problem, and not grouped transactions itself.

![amount0_wrong](https://user-images.githubusercontent.com/15806049/73002376-3ba9da80-3e04-11ea-82dc-8f20d8fa5bd1.png)

**Comment by Bone008** [comment]
Good find! Identified as very hard to find edge case, where due to floating point precision, the total sum of the transaction group can end up being a very small negative number. While I account for those in the amount comparison logic, due to the rounding feature it was incorrectly rounded to -1€ instead of 0€ before comparison ....
