### ISSUE TITLE
Billing period in the future causes Analytics to break

### ISSUE THREAD

**Issue by nayrutes** [Bone008/finance-tracker#276]
- Select existing transaction and select billing period Days, custom
- Enter a 3 days period in the middle of a future month
- Open Analytics Screen

=> Page is unresponsive. If it manages to load, income and expenses are not visible and in the Overview section hundreds of empty lines exist (which creation is probably the reason for the unresponsive page before)

**Comment by Bone008** [comment]
Hmm I cannot reproduce this for days that are reasonably close in the future. But it can happen if the custom date is extremely far away, since the analytics page fills in "gaps" for empty months, so if you enter a date 100 years from now it would generate and display 1200 months. Maybe something like that happened by accident in your data?

**Comment by nayrutes** [comment]
![image](https://github.com/Bone008/finance-tracker/assets/33394281/ec629b5d-3739-40cc-9601-09cadafa28b3)
It did... I forgot to save and found it again.
Thx :)
